### ISSUE TITLE
Tools charging bug

### ISSUE THREAD

**Issue by Pyromanc3r** [CrossVas/GraviSuiteReforged-1.5.2#11]
Just noticed that since version `2.2.2k` the tools are not recharging from lappacks and gravichestplate. Only IC2 tools can recharge.

**Comment by CrossVas** [comment]
Could you please check the latest version and provide more information about what tool doesn't charge, because I didn't touch them since first implemented and it works as intended on my side.

Upd: also what version?

**Comment by CrossVas** [comment]
I think I found the issue. Will be fixed next patch.
