### ISSUE TITLE
Add Ultimate Solar Helmet.

### ISSUE THREAD

**Issue by Pilad** [CrossVas/GraviSuiteReforged-1.5.2#13]
Please add Ultimate Solar Helmet.

**Comment by CrossVas** [comment]
Ultimate Solar Helmet is part of Advanced Solar Panels, not GraviSuite 
![image](https://github.com/user-attachments/assets/d2b794d3-212c-403b-b631-8538c896aa2a)

**Comment by Pilad** [comment]
> Ultimate Solar Helmet is part of Advanced Solar Panels, not GraviSuite ![image](https://private-user-images.githubusercontent.com/25727222/390818771-d2b794d3-212c-403b-b631-8538c896aa2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MjQ3MzAsIm5iZiI6MTczMjgyNDQzMCwicGF0aCI6Ii8yNTcyNzIyMi8zOTA4MTg3NzEtZDJiNzk0ZDMtMjEyYy00MDNiLWI2MzEtODUzOGM4OTZhYTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDIwMDcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmY2M0Zjk5MzdmOGI1ZjQyODIzMjRmN2M3Njg2YzQxMjllODQ3NjNmY2U1Y2E1NjAxYTg0MWEwMjliYzcwODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Sq4VHyWzYkMq4Qt4_JJ84lT5W-sgtClDqO081dDLFV4)

Open mod GS: solar helmet.
![изображение](https://github.com/user-attachments/assets/4ef3e74b-647b-4f54-afe2-a5e249f75705)
![изображение](https://github.com/user-attachments/assets/27af1fd9-ae32-4f97-a12e-e8c5fe95fa5d)

**Comment by Pilad** [comment]
![изображение](https://github.com/user-attachments/assets/c808f41f-46cf-416f-b406-3adddae62d8f)
![изображение](https://github.com/user-attachments/assets/b9a97d36-bd1a-4a1b-9f00-a4270039437d)

**Comment by CrossVas** [comment]
> Open mod GS: solar helmet.

Let's ignore the fact that the `Ultimate Helmet` present in GraviSuite was just an artifact and has no recipe, it would require me to have AdvancedSolarPanels installed in order to make the helmet. One question, why?

So knowing that it is clearly a duplication (for absolute no reason) of `Ultimate Solar Helmet` what are you trying to achieve?
The answer is no.
