### ISSUE TITLE
A couple of wrong recipes

### ISSUE THREAD

**Issue by Pyromanc3r** [CrossVas/GraviSuiteReforged-1.5.2#2]
I compared the mod with the original and found inaccuracies in the recipes.
1. In your recipe Gravi chestplate does not use Gravitational Engines
![2024-04-25_12 04 09](https://github.com/CrossVas/GraviSuiteReforged/assets/17619385/775ec249-1e80-4a66-bfa8-72b3f3a22ac0)

Original:
![2024-04-25_11 50 12](https://github.com/CrossVas/GraviSuiteReforged/assets/17619385/a9464281-d9a2-4883-a22b-fb2a62cffb9a)

2. Ultimate Lappack is created from regular IC2 Lappack, not Advanced Lappack. Although to be fair the original addon used both. But I think it makes more sense to create it from the Advanced version.
![2024-04-25_12 03 56](https://github.com/CrossVas/GraviSuiteReforged/assets/17619385/a2bdf278-551f-4fd4-8460-cd719b3b9076)

Original:
![2024-04-25_11 50 16](https://github.com/CrossVas/GraviSuiteReforged/assets/17619385/b155164a-1fa1-4e12-9a4d-8754ee948ffd)

**Comment by CrossVas** [comment]
Yes, that's not right. Will be fixed very soon.

**Comment by CrossVas** [comment]
Yes, this was a stupid copy-paste thing. Should be fixed now.
![image](https://github.com/CrossVas/GraviSuiteReforged/assets/25727222/efbba25b-7a52-49de-9e13-8b2e9a903c4b)
