### ISSUE TITLE
Advanced Chainsaw

### ISSUE THREAD

**Issue by Pyromanc3r** [CrossVas/GraviSuiteReforged-1.5.2#3]
Tree Capitator mode does not support trees from other mods. I tested on trees from Biomes O' Plenty, IC2 Rubber tree and Mine Factory Reloaded rubber tree.
![2024-04-25_17 31 15](https://github.com/CrossVas/GraviSuiteReforged/assets/17619385/5efdff16-a965-448a-a5b0-19a6c59c92f6)

There is also an incorrect behavior when cutting the tree trunk 2x2 blocks (Jungle tree for example). It only cuts 4 blocks up.
![2024-04-25_17 30 26](https://github.com/CrossVas/GraviSuiteReforged/assets/17619385/866486c6-5785-4aee-a0d4-b151399155db)

**Comment by Pyromanc3r** [comment]
I also want to mention that at the moment this saw is felling trees almost instantly in one click

**Comment by CrossVas** [comment]
`veinPos` logic was improved, now it should work as intended with a limit of 128 blocks, that's the value I won't change for performance reasons.

Do note that `veinPos` works as a block detector, not as a structure detector (trees, buildings, etc.), so when mining logs that are not trees, better switch `TreeCapitator` mode off for `Advanced Chainsaw` and `Extended Vein` for `Vajra`.

As for the efficiency of `Advanced Chainsaw`, my version uses 30F, while the original mod uses 35F which is too much IMO, this won't change, sorry. 

EDIT: Also, `Advanced Chainsaw` is looking for `log*` oreDict value so if the tree is not cut instantly using capitator mode, it means that the log isn't added to `OreDictionary` as `log*`

**Comment by Pyromanc3r** [comment]
Sorry to bother you again, but maybe I don't understand something or something is not working correctly.
With IC2 trees it's clear since mod don't have a proper oreDict. Ok.
![2024-04-26_15 28 03](https://github.com/CrossVas/GraviSuiteReforged/assets/17619385/e71a40d5-24d7-4302-8cc5-51b9e5901929)

But with the Biomes O' Plenty mod something strange happens (I'm using version 0.5.9.4 if it matters). Tree Capitator mode doesn't work. The NEIPlugins (https://bitbucket.org/mistaqur/nei_plugins/wiki/NEI%201.5.x.x) shows that there is a proper OreDictionary. Although Forestry is fully supported and has the same OreDictionary and everything works as it should.
![2024-04-26_15 26 21](https://github.com/CrossVas/GraviSuiteReforged/assets/17619385/b6a76d0c-cca8-4372-b437-cc63fe925497)
![2024-04-26_15 26 26](https://github.com/CrossVas/GraviSuiteReforged/assets/17619385/8b1429f4-3d92-43d2-9af4-65a727445b08)

**Comment by CrossVas** [comment]
Ic2 rubber should be really easy to fix either by adding it to log oredict or by checking for wood value as well. As for BoP trees, there might be something going on about meta values. Gonna investigate this more tomorrow.

**Comment by CrossVas** [comment]
At this point I'm thinking about giving up on this mode and just provide support for `TreeCapitator` mod.
