### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ThePixelbrain** [CrossVas/GraviSuiteReforged-1.5.2#4]
What's the license of this project? There is no license file or any mention about this in the README.
Could you please clarify that so we know what we're allowed to do with it?

**Comment by CrossVas** [comment]
You don't need that. If there is no license, it means it's ARR. Either by me, or by original author.

EDIT:
Code by CrossVas
Textures by [SeNtiMeL](https://forum.industrial-craft.net/thread/6915-ic2-exp-1-7-10-gravitation-suite-v2-0-3/)
